// Copyright (c) 2005-2014 Code Synthesis Tools CC
//
// This program was generated by CodeSynthesis XSD, an XML Schema to
// C++ data binding compiler.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
// In addition, as a special exception, Code Synthesis Tools CC gives
// permission to link this program with the Xerces-C++ library (or with
// modified versions of Xerces-C++ that use the same license as Xerces-C++),
// and distribute linked combinations including the two. You must obey
// the GNU General Public License version 2 in all respects for all of
// the code used other than Xerces-C++. If you modify this copy of the
// program, you may extend this exception to your version of the program,
// but you are not obligated to do so. If you do not wish to do so, delete
// this exception statement from your version.
//
// Furthermore, Code Synthesis Tools CC makes a special exception for
// the Free/Libre and Open Source Software (FLOSS) which is described
// in the accompanying FLOSSE file.
//

// Begin prologue.
//
//
// End prologue.

#include <xsd/cxx/pre.hxx>

#include "featurerevolve.h"

namespace prj
{
  namespace srl
  {
    // FeatureRevolve
    // 

    const FeatureRevolve::FeatureBaseType& FeatureRevolve::
    featureBase () const
    {
      return this->featureBase_.get ();
    }

    FeatureRevolve::FeatureBaseType& FeatureRevolve::
    featureBase ()
    {
      return this->featureBase_.get ();
    }

    void FeatureRevolve::
    featureBase (const FeatureBaseType& x)
    {
      this->featureBase_.set (x);
    }

    void FeatureRevolve::
    featureBase (::std::unique_ptr< FeatureBaseType > x)
    {
      this->featureBase_.set (std::move (x));
    }

    const FeatureRevolve::PicksType& FeatureRevolve::
    picks () const
    {
      return this->picks_.get ();
    }

    FeatureRevolve::PicksType& FeatureRevolve::
    picks ()
    {
      return this->picks_.get ();
    }

    void FeatureRevolve::
    picks (const PicksType& x)
    {
      this->picks_.set (x);
    }

    void FeatureRevolve::
    picks (::std::unique_ptr< PicksType > x)
    {
      this->picks_.set (std::move (x));
    }

    const FeatureRevolve::AxisPicksType& FeatureRevolve::
    axisPicks () const
    {
      return this->axisPicks_.get ();
    }

    FeatureRevolve::AxisPicksType& FeatureRevolve::
    axisPicks ()
    {
      return this->axisPicks_.get ();
    }

    void FeatureRevolve::
    axisPicks (const AxisPicksType& x)
    {
      this->axisPicks_.set (x);
    }

    void FeatureRevolve::
    axisPicks (::std::unique_ptr< AxisPicksType > x)
    {
      this->axisPicks_.set (std::move (x));
    }

    const FeatureRevolve::AxisOriginType& FeatureRevolve::
    axisOrigin () const
    {
      return this->axisOrigin_.get ();
    }

    FeatureRevolve::AxisOriginType& FeatureRevolve::
    axisOrigin ()
    {
      return this->axisOrigin_.get ();
    }

    void FeatureRevolve::
    axisOrigin (const AxisOriginType& x)
    {
      this->axisOrigin_.set (x);
    }

    void FeatureRevolve::
    axisOrigin (::std::unique_ptr< AxisOriginType > x)
    {
      this->axisOrigin_.set (std::move (x));
    }

    const FeatureRevolve::AxisOriginLabelType& FeatureRevolve::
    axisOriginLabel () const
    {
      return this->axisOriginLabel_.get ();
    }

    FeatureRevolve::AxisOriginLabelType& FeatureRevolve::
    axisOriginLabel ()
    {
      return this->axisOriginLabel_.get ();
    }

    void FeatureRevolve::
    axisOriginLabel (const AxisOriginLabelType& x)
    {
      this->axisOriginLabel_.set (x);
    }

    void FeatureRevolve::
    axisOriginLabel (::std::unique_ptr< AxisOriginLabelType > x)
    {
      this->axisOriginLabel_.set (std::move (x));
    }

    const FeatureRevolve::AxisDirectionType& FeatureRevolve::
    axisDirection () const
    {
      return this->axisDirection_.get ();
    }

    FeatureRevolve::AxisDirectionType& FeatureRevolve::
    axisDirection ()
    {
      return this->axisDirection_.get ();
    }

    void FeatureRevolve::
    axisDirection (const AxisDirectionType& x)
    {
      this->axisDirection_.set (x);
    }

    void FeatureRevolve::
    axisDirection (::std::unique_ptr< AxisDirectionType > x)
    {
      this->axisDirection_.set (std::move (x));
    }

    const FeatureRevolve::AxisDirectionLabelType& FeatureRevolve::
    axisDirectionLabel () const
    {
      return this->axisDirectionLabel_.get ();
    }

    FeatureRevolve::AxisDirectionLabelType& FeatureRevolve::
    axisDirectionLabel ()
    {
      return this->axisDirectionLabel_.get ();
    }

    void FeatureRevolve::
    axisDirectionLabel (const AxisDirectionLabelType& x)
    {
      this->axisDirectionLabel_.set (x);
    }

    void FeatureRevolve::
    axisDirectionLabel (::std::unique_ptr< AxisDirectionLabelType > x)
    {
      this->axisDirectionLabel_.set (std::move (x));
    }

    const FeatureRevolve::AngleType& FeatureRevolve::
    angle () const
    {
      return this->angle_.get ();
    }

    FeatureRevolve::AngleType& FeatureRevolve::
    angle ()
    {
      return this->angle_.get ();
    }

    void FeatureRevolve::
    angle (const AngleType& x)
    {
      this->angle_.set (x);
    }

    void FeatureRevolve::
    angle (::std::unique_ptr< AngleType > x)
    {
      this->angle_.set (std::move (x));
    }

    const FeatureRevolve::AngleLabelType& FeatureRevolve::
    angleLabel () const
    {
      return this->angleLabel_.get ();
    }

    FeatureRevolve::AngleLabelType& FeatureRevolve::
    angleLabel ()
    {
      return this->angleLabel_.get ();
    }

    void FeatureRevolve::
    angleLabel (const AngleLabelType& x)
    {
      this->angleLabel_.set (x);
    }

    void FeatureRevolve::
    angleLabel (::std::unique_ptr< AngleLabelType > x)
    {
      this->angleLabel_.set (std::move (x));
    }

    const FeatureRevolve::AxisTypeType& FeatureRevolve::
    axisType () const
    {
      return this->axisType_.get ();
    }

    FeatureRevolve::AxisTypeType& FeatureRevolve::
    axisType ()
    {
      return this->axisType_.get ();
    }

    void FeatureRevolve::
    axisType (const AxisTypeType& x)
    {
      this->axisType_.set (x);
    }

    const FeatureRevolve::GeneratedMapType& FeatureRevolve::
    generatedMap () const
    {
      return this->generatedMap_.get ();
    }

    FeatureRevolve::GeneratedMapType& FeatureRevolve::
    generatedMap ()
    {
      return this->generatedMap_.get ();
    }

    void FeatureRevolve::
    generatedMap (const GeneratedMapType& x)
    {
      this->generatedMap_.set (x);
    }

    void FeatureRevolve::
    generatedMap (::std::unique_ptr< GeneratedMapType > x)
    {
      this->generatedMap_.set (std::move (x));
    }

    const FeatureRevolve::LastMapType& FeatureRevolve::
    lastMap () const
    {
      return this->lastMap_.get ();
    }

    FeatureRevolve::LastMapType& FeatureRevolve::
    lastMap ()
    {
      return this->lastMap_.get ();
    }

    void FeatureRevolve::
    lastMap (const LastMapType& x)
    {
      this->lastMap_.set (x);
    }

    void FeatureRevolve::
    lastMap (::std::unique_ptr< LastMapType > x)
    {
      this->lastMap_.set (std::move (x));
    }

    const FeatureRevolve::OWireMapType& FeatureRevolve::
    oWireMap () const
    {
      return this->oWireMap_.get ();
    }

    FeatureRevolve::OWireMapType& FeatureRevolve::
    oWireMap ()
    {
      return this->oWireMap_.get ();
    }

    void FeatureRevolve::
    oWireMap (const OWireMapType& x)
    {
      this->oWireMap_.set (x);
    }

    void FeatureRevolve::
    oWireMap (::std::unique_ptr< OWireMapType > x)
    {
      this->oWireMap_.set (std::move (x));
    }
  }
}

#include <xsd/cxx/xml/dom/parsing-source.hxx>

namespace prj
{
  namespace srl
  {
    // FeatureRevolve
    //

    FeatureRevolve::
    FeatureRevolve (const FeatureBaseType& featureBase,
                    const PicksType& picks,
                    const AxisPicksType& axisPicks,
                    const AxisOriginType& axisOrigin,
                    const AxisOriginLabelType& axisOriginLabel,
                    const AxisDirectionType& axisDirection,
                    const AxisDirectionLabelType& axisDirectionLabel,
                    const AngleType& angle,
                    const AngleLabelType& angleLabel,
                    const AxisTypeType& axisType,
                    const GeneratedMapType& generatedMap,
                    const LastMapType& lastMap,
                    const OWireMapType& oWireMap)
    : ::xml_schema::Type (),
      featureBase_ (featureBase, this),
      picks_ (picks, this),
      axisPicks_ (axisPicks, this),
      axisOrigin_ (axisOrigin, this),
      axisOriginLabel_ (axisOriginLabel, this),
      axisDirection_ (axisDirection, this),
      axisDirectionLabel_ (axisDirectionLabel, this),
      angle_ (angle, this),
      angleLabel_ (angleLabel, this),
      axisType_ (axisType, this),
      generatedMap_ (generatedMap, this),
      lastMap_ (lastMap, this),
      oWireMap_ (oWireMap, this)
    {
    }

    FeatureRevolve::
    FeatureRevolve (::std::unique_ptr< FeatureBaseType > featureBase,
                    ::std::unique_ptr< PicksType > picks,
                    ::std::unique_ptr< AxisPicksType > axisPicks,
                    ::std::unique_ptr< AxisOriginType > axisOrigin,
                    ::std::unique_ptr< AxisOriginLabelType > axisOriginLabel,
                    ::std::unique_ptr< AxisDirectionType > axisDirection,
                    ::std::unique_ptr< AxisDirectionLabelType > axisDirectionLabel,
                    ::std::unique_ptr< AngleType > angle,
                    ::std::unique_ptr< AngleLabelType > angleLabel,
                    const AxisTypeType& axisType,
                    ::std::unique_ptr< GeneratedMapType > generatedMap,
                    ::std::unique_ptr< LastMapType > lastMap,
                    ::std::unique_ptr< OWireMapType > oWireMap)
    : ::xml_schema::Type (),
      featureBase_ (std::move (featureBase), this),
      picks_ (std::move (picks), this),
      axisPicks_ (std::move (axisPicks), this),
      axisOrigin_ (std::move (axisOrigin), this),
      axisOriginLabel_ (std::move (axisOriginLabel), this),
      axisDirection_ (std::move (axisDirection), this),
      axisDirectionLabel_ (std::move (axisDirectionLabel), this),
      angle_ (std::move (angle), this),
      angleLabel_ (std::move (angleLabel), this),
      axisType_ (axisType, this),
      generatedMap_ (std::move (generatedMap), this),
      lastMap_ (std::move (lastMap), this),
      oWireMap_ (std::move (oWireMap), this)
    {
    }

    FeatureRevolve::
    FeatureRevolve (const FeatureRevolve& x,
                    ::xml_schema::Flags f,
                    ::xml_schema::Container* c)
    : ::xml_schema::Type (x, f, c),
      featureBase_ (x.featureBase_, f, this),
      picks_ (x.picks_, f, this),
      axisPicks_ (x.axisPicks_, f, this),
      axisOrigin_ (x.axisOrigin_, f, this),
      axisOriginLabel_ (x.axisOriginLabel_, f, this),
      axisDirection_ (x.axisDirection_, f, this),
      axisDirectionLabel_ (x.axisDirectionLabel_, f, this),
      angle_ (x.angle_, f, this),
      angleLabel_ (x.angleLabel_, f, this),
      axisType_ (x.axisType_, f, this),
      generatedMap_ (x.generatedMap_, f, this),
      lastMap_ (x.lastMap_, f, this),
      oWireMap_ (x.oWireMap_, f, this)
    {
    }

    FeatureRevolve::
    FeatureRevolve (const ::xercesc::DOMElement& e,
                    ::xml_schema::Flags f,
                    ::xml_schema::Container* c)
    : ::xml_schema::Type (e, f | ::xml_schema::Flags::base, c),
      featureBase_ (this),
      picks_ (this),
      axisPicks_ (this),
      axisOrigin_ (this),
      axisOriginLabel_ (this),
      axisDirection_ (this),
      axisDirectionLabel_ (this),
      angle_ (this),
      angleLabel_ (this),
      axisType_ (this),
      generatedMap_ (this),
      lastMap_ (this),
      oWireMap_ (this)
    {
      if ((f & ::xml_schema::Flags::base) == 0)
      {
        ::xsd::cxx::xml::dom::parser< char > p (e, true, false, false);
        this->parse (p, f);
      }
    }

    void FeatureRevolve::
    parse (::xsd::cxx::xml::dom::parser< char >& p,
           ::xml_schema::Flags f)
    {
      for (; p.more_content (); p.next_content (false))
      {
        const ::xercesc::DOMElement& i (p.cur_element ());
        const ::xsd::cxx::xml::qualified_name< char > n (
          ::xsd::cxx::xml::dom::name< char > (i));

        // featureBase
        //
        if (n.name () == "featureBase" && n.namespace_ ().empty ())
        {
          ::std::unique_ptr< FeatureBaseType > r (
            FeatureBaseTraits::create (i, f, this));

          if (!featureBase_.present ())
          {
            this->featureBase_.set (::std::move (r));
            continue;
          }
        }

        // picks
        //
        if (n.name () == "picks" && n.namespace_ ().empty ())
        {
          ::std::unique_ptr< PicksType > r (
            PicksTraits::create (i, f, this));

          if (!picks_.present ())
          {
            this->picks_.set (::std::move (r));
            continue;
          }
        }

        // axisPicks
        //
        if (n.name () == "axisPicks" && n.namespace_ ().empty ())
        {
          ::std::unique_ptr< AxisPicksType > r (
            AxisPicksTraits::create (i, f, this));

          if (!axisPicks_.present ())
          {
            this->axisPicks_.set (::std::move (r));
            continue;
          }
        }

        // axisOrigin
        //
        if (n.name () == "axisOrigin" && n.namespace_ ().empty ())
        {
          ::std::unique_ptr< AxisOriginType > r (
            AxisOriginTraits::create (i, f, this));

          if (!axisOrigin_.present ())
          {
            this->axisOrigin_.set (::std::move (r));
            continue;
          }
        }

        // axisOriginLabel
        //
        if (n.name () == "axisOriginLabel" && n.namespace_ ().empty ())
        {
          ::std::unique_ptr< AxisOriginLabelType > r (
            AxisOriginLabelTraits::create (i, f, this));

          if (!axisOriginLabel_.present ())
          {
            this->axisOriginLabel_.set (::std::move (r));
            continue;
          }
        }

        // axisDirection
        //
        if (n.name () == "axisDirection" && n.namespace_ ().empty ())
        {
          ::std::unique_ptr< AxisDirectionType > r (
            AxisDirectionTraits::create (i, f, this));

          if (!axisDirection_.present ())
          {
            this->axisDirection_.set (::std::move (r));
            continue;
          }
        }

        // axisDirectionLabel
        //
        if (n.name () == "axisDirectionLabel" && n.namespace_ ().empty ())
        {
          ::std::unique_ptr< AxisDirectionLabelType > r (
            AxisDirectionLabelTraits::create (i, f, this));

          if (!axisDirectionLabel_.present ())
          {
            this->axisDirectionLabel_.set (::std::move (r));
            continue;
          }
        }

        // angle
        //
        if (n.name () == "angle" && n.namespace_ ().empty ())
        {
          ::std::unique_ptr< AngleType > r (
            AngleTraits::create (i, f, this));

          if (!angle_.present ())
          {
            this->angle_.set (::std::move (r));
            continue;
          }
        }

        // angleLabel
        //
        if (n.name () == "angleLabel" && n.namespace_ ().empty ())
        {
          ::std::unique_ptr< AngleLabelType > r (
            AngleLabelTraits::create (i, f, this));

          if (!angleLabel_.present ())
          {
            this->angleLabel_.set (::std::move (r));
            continue;
          }
        }

        // axisType
        //
        if (n.name () == "axisType" && n.namespace_ ().empty ())
        {
          if (!axisType_.present ())
          {
            this->axisType_.set (AxisTypeTraits::create (i, f, this));
            continue;
          }
        }

        // generatedMap
        //
        if (n.name () == "generatedMap" && n.namespace_ ().empty ())
        {
          ::std::unique_ptr< GeneratedMapType > r (
            GeneratedMapTraits::create (i, f, this));

          if (!generatedMap_.present ())
          {
            this->generatedMap_.set (::std::move (r));
            continue;
          }
        }

        // lastMap
        //
        if (n.name () == "lastMap" && n.namespace_ ().empty ())
        {
          ::std::unique_ptr< LastMapType > r (
            LastMapTraits::create (i, f, this));

          if (!lastMap_.present ())
          {
            this->lastMap_.set (::std::move (r));
            continue;
          }
        }

        // oWireMap
        //
        if (n.name () == "oWireMap" && n.namespace_ ().empty ())
        {
          ::std::unique_ptr< OWireMapType > r (
            OWireMapTraits::create (i, f, this));

          if (!oWireMap_.present ())
          {
            this->oWireMap_.set (::std::move (r));
            continue;
          }
        }

        break;
      }

      if (!featureBase_.present ())
      {
        throw ::xsd::cxx::tree::expected_element< char > (
          "featureBase",
          "");
      }

      if (!picks_.present ())
      {
        throw ::xsd::cxx::tree::expected_element< char > (
          "picks",
          "");
      }

      if (!axisPicks_.present ())
      {
        throw ::xsd::cxx::tree::expected_element< char > (
          "axisPicks",
          "");
      }

      if (!axisOrigin_.present ())
      {
        throw ::xsd::cxx::tree::expected_element< char > (
          "axisOrigin",
          "");
      }

      if (!axisOriginLabel_.present ())
      {
        throw ::xsd::cxx::tree::expected_element< char > (
          "axisOriginLabel",
          "");
      }

      if (!axisDirection_.present ())
      {
        throw ::xsd::cxx::tree::expected_element< char > (
          "axisDirection",
          "");
      }

      if (!axisDirectionLabel_.present ())
      {
        throw ::xsd::cxx::tree::expected_element< char > (
          "axisDirectionLabel",
          "");
      }

      if (!angle_.present ())
      {
        throw ::xsd::cxx::tree::expected_element< char > (
          "angle",
          "");
      }

      if (!angleLabel_.present ())
      {
        throw ::xsd::cxx::tree::expected_element< char > (
          "angleLabel",
          "");
      }

      if (!axisType_.present ())
      {
        throw ::xsd::cxx::tree::expected_element< char > (
          "axisType",
          "");
      }

      if (!generatedMap_.present ())
      {
        throw ::xsd::cxx::tree::expected_element< char > (
          "generatedMap",
          "");
      }

      if (!lastMap_.present ())
      {
        throw ::xsd::cxx::tree::expected_element< char > (
          "lastMap",
          "");
      }

      if (!oWireMap_.present ())
      {
        throw ::xsd::cxx::tree::expected_element< char > (
          "oWireMap",
          "");
      }
    }

    FeatureRevolve* FeatureRevolve::
    _clone (::xml_schema::Flags f,
            ::xml_schema::Container* c) const
    {
      return new class FeatureRevolve (*this, f, c);
    }

    FeatureRevolve& FeatureRevolve::
    operator= (const FeatureRevolve& x)
    {
      if (this != &x)
      {
        static_cast< ::xml_schema::Type& > (*this) = x;
        this->featureBase_ = x.featureBase_;
        this->picks_ = x.picks_;
        this->axisPicks_ = x.axisPicks_;
        this->axisOrigin_ = x.axisOrigin_;
        this->axisOriginLabel_ = x.axisOriginLabel_;
        this->axisDirection_ = x.axisDirection_;
        this->axisDirectionLabel_ = x.axisDirectionLabel_;
        this->angle_ = x.angle_;
        this->angleLabel_ = x.angleLabel_;
        this->axisType_ = x.axisType_;
        this->generatedMap_ = x.generatedMap_;
        this->lastMap_ = x.lastMap_;
        this->oWireMap_ = x.oWireMap_;
      }

      return *this;
    }

    FeatureRevolve::
    ~FeatureRevolve ()
    {
    }
  }
}

#include <istream>
#include <xsd/cxx/xml/sax/std-input-source.hxx>
#include <xsd/cxx/tree/error-handler.hxx>

namespace prj
{
  namespace srl
  {
    ::std::unique_ptr< ::prj::srl::FeatureRevolve >
    revolve (const ::std::string& u,
             ::xml_schema::Flags f,
             const ::xml_schema::Properties& p)
    {
      ::xsd::cxx::xml::auto_initializer i (
        (f & ::xml_schema::Flags::dont_initialize) == 0,
        (f & ::xml_schema::Flags::keep_dom) == 0);

      ::xsd::cxx::tree::error_handler< char > h;

      ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
        ::xsd::cxx::xml::dom::parse< char > (
          u, h, p, f));

      h.throw_if_failed< ::xsd::cxx::tree::parsing< char > > ();

      return ::std::unique_ptr< ::prj::srl::FeatureRevolve > (
        ::prj::srl::revolve (
          std::move (d), f | ::xml_schema::Flags::own_dom, p));
    }

    ::std::unique_ptr< ::prj::srl::FeatureRevolve >
    revolve (const ::std::string& u,
             ::xml_schema::ErrorHandler& h,
             ::xml_schema::Flags f,
             const ::xml_schema::Properties& p)
    {
      ::xsd::cxx::xml::auto_initializer i (
        (f & ::xml_schema::Flags::dont_initialize) == 0,
        (f & ::xml_schema::Flags::keep_dom) == 0);

      ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
        ::xsd::cxx::xml::dom::parse< char > (
          u, h, p, f));

      if (!d.get ())
        throw ::xsd::cxx::tree::parsing< char > ();

      return ::std::unique_ptr< ::prj::srl::FeatureRevolve > (
        ::prj::srl::revolve (
          std::move (d), f | ::xml_schema::Flags::own_dom, p));
    }

    ::std::unique_ptr< ::prj::srl::FeatureRevolve >
    revolve (const ::std::string& u,
             ::xercesc::DOMErrorHandler& h,
             ::xml_schema::Flags f,
             const ::xml_schema::Properties& p)
    {
      ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
        ::xsd::cxx::xml::dom::parse< char > (
          u, h, p, f));

      if (!d.get ())
        throw ::xsd::cxx::tree::parsing< char > ();

      return ::std::unique_ptr< ::prj::srl::FeatureRevolve > (
        ::prj::srl::revolve (
          std::move (d), f | ::xml_schema::Flags::own_dom, p));
    }

    ::std::unique_ptr< ::prj::srl::FeatureRevolve >
    revolve (::std::istream& is,
             ::xml_schema::Flags f,
             const ::xml_schema::Properties& p)
    {
      ::xsd::cxx::xml::auto_initializer i (
        (f & ::xml_schema::Flags::dont_initialize) == 0,
        (f & ::xml_schema::Flags::keep_dom) == 0);

      ::xsd::cxx::xml::sax::std_input_source isrc (is);
      return ::prj::srl::revolve (isrc, f, p);
    }

    ::std::unique_ptr< ::prj::srl::FeatureRevolve >
    revolve (::std::istream& is,
             ::xml_schema::ErrorHandler& h,
             ::xml_schema::Flags f,
             const ::xml_schema::Properties& p)
    {
      ::xsd::cxx::xml::auto_initializer i (
        (f & ::xml_schema::Flags::dont_initialize) == 0,
        (f & ::xml_schema::Flags::keep_dom) == 0);

      ::xsd::cxx::xml::sax::std_input_source isrc (is);
      return ::prj::srl::revolve (isrc, h, f, p);
    }

    ::std::unique_ptr< ::prj::srl::FeatureRevolve >
    revolve (::std::istream& is,
             ::xercesc::DOMErrorHandler& h,
             ::xml_schema::Flags f,
             const ::xml_schema::Properties& p)
    {
      ::xsd::cxx::xml::sax::std_input_source isrc (is);
      return ::prj::srl::revolve (isrc, h, f, p);
    }

    ::std::unique_ptr< ::prj::srl::FeatureRevolve >
    revolve (::std::istream& is,
             const ::std::string& sid,
             ::xml_schema::Flags f,
             const ::xml_schema::Properties& p)
    {
      ::xsd::cxx::xml::auto_initializer i (
        (f & ::xml_schema::Flags::dont_initialize) == 0,
        (f & ::xml_schema::Flags::keep_dom) == 0);

      ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
      return ::prj::srl::revolve (isrc, f, p);
    }

    ::std::unique_ptr< ::prj::srl::FeatureRevolve >
    revolve (::std::istream& is,
             const ::std::string& sid,
             ::xml_schema::ErrorHandler& h,
             ::xml_schema::Flags f,
             const ::xml_schema::Properties& p)
    {
      ::xsd::cxx::xml::auto_initializer i (
        (f & ::xml_schema::Flags::dont_initialize) == 0,
        (f & ::xml_schema::Flags::keep_dom) == 0);

      ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
      return ::prj::srl::revolve (isrc, h, f, p);
    }

    ::std::unique_ptr< ::prj::srl::FeatureRevolve >
    revolve (::std::istream& is,
             const ::std::string& sid,
             ::xercesc::DOMErrorHandler& h,
             ::xml_schema::Flags f,
             const ::xml_schema::Properties& p)
    {
      ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
      return ::prj::srl::revolve (isrc, h, f, p);
    }

    ::std::unique_ptr< ::prj::srl::FeatureRevolve >
    revolve (::xercesc::InputSource& i,
             ::xml_schema::Flags f,
             const ::xml_schema::Properties& p)
    {
      ::xsd::cxx::tree::error_handler< char > h;

      ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
        ::xsd::cxx::xml::dom::parse< char > (
          i, h, p, f));

      h.throw_if_failed< ::xsd::cxx::tree::parsing< char > > ();

      return ::std::unique_ptr< ::prj::srl::FeatureRevolve > (
        ::prj::srl::revolve (
          std::move (d), f | ::xml_schema::Flags::own_dom, p));
    }

    ::std::unique_ptr< ::prj::srl::FeatureRevolve >
    revolve (::xercesc::InputSource& i,
             ::xml_schema::ErrorHandler& h,
             ::xml_schema::Flags f,
             const ::xml_schema::Properties& p)
    {
      ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
        ::xsd::cxx::xml::dom::parse< char > (
          i, h, p, f));

      if (!d.get ())
        throw ::xsd::cxx::tree::parsing< char > ();

      return ::std::unique_ptr< ::prj::srl::FeatureRevolve > (
        ::prj::srl::revolve (
          std::move (d), f | ::xml_schema::Flags::own_dom, p));
    }

    ::std::unique_ptr< ::prj::srl::FeatureRevolve >
    revolve (::xercesc::InputSource& i,
             ::xercesc::DOMErrorHandler& h,
             ::xml_schema::Flags f,
             const ::xml_schema::Properties& p)
    {
      ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
        ::xsd::cxx::xml::dom::parse< char > (
          i, h, p, f));

      if (!d.get ())
        throw ::xsd::cxx::tree::parsing< char > ();

      return ::std::unique_ptr< ::prj::srl::FeatureRevolve > (
        ::prj::srl::revolve (
          std::move (d), f | ::xml_schema::Flags::own_dom, p));
    }

    ::std::unique_ptr< ::prj::srl::FeatureRevolve >
    revolve (const ::xercesc::DOMDocument& doc,
             ::xml_schema::Flags f,
             const ::xml_schema::Properties& p)
    {
      if (f & ::xml_schema::Flags::keep_dom)
      {
        ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
          static_cast< ::xercesc::DOMDocument* > (doc.cloneNode (true)));

        return ::std::unique_ptr< ::prj::srl::FeatureRevolve > (
          ::prj::srl::revolve (
            std::move (d), f | ::xml_schema::Flags::own_dom, p));
      }

      const ::xercesc::DOMElement& e (*doc.getDocumentElement ());
      const ::xsd::cxx::xml::qualified_name< char > n (
        ::xsd::cxx::xml::dom::name< char > (e));

      if (n.name () == "revolve" &&
          n.namespace_ () == "http://www.cadseer.com/prj/srl")
      {
        ::std::unique_ptr< ::prj::srl::FeatureRevolve > r (
          ::xsd::cxx::tree::traits< ::prj::srl::FeatureRevolve, char >::create (
            e, f, 0));
        return r;
      }

      throw ::xsd::cxx::tree::unexpected_element < char > (
        n.name (),
        n.namespace_ (),
        "revolve",
        "http://www.cadseer.com/prj/srl");
    }

    ::std::unique_ptr< ::prj::srl::FeatureRevolve >
    revolve (::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d,
             ::xml_schema::Flags f,
             const ::xml_schema::Properties&)
    {
      ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > c (
        ((f & ::xml_schema::Flags::keep_dom) &&
         !(f & ::xml_schema::Flags::own_dom))
        ? static_cast< ::xercesc::DOMDocument* > (d->cloneNode (true))
        : 0);

      ::xercesc::DOMDocument& doc (c.get () ? *c : *d);
      const ::xercesc::DOMElement& e (*doc.getDocumentElement ());

      const ::xsd::cxx::xml::qualified_name< char > n (
        ::xsd::cxx::xml::dom::name< char > (e));

      if (f & ::xml_schema::Flags::keep_dom)
        doc.setUserData (::xml_schema::dom::tree_node_key,
                         (c.get () ? &c : &d),
                         0);

      if (n.name () == "revolve" &&
          n.namespace_ () == "http://www.cadseer.com/prj/srl")
      {
        ::std::unique_ptr< ::prj::srl::FeatureRevolve > r (
          ::xsd::cxx::tree::traits< ::prj::srl::FeatureRevolve, char >::create (
            e, f, 0));
        return r;
      }

      throw ::xsd::cxx::tree::unexpected_element < char > (
        n.name (),
        n.namespace_ (),
        "revolve",
        "http://www.cadseer.com/prj/srl");
    }
  }
}

#include <ostream>
#include <xsd/cxx/tree/error-handler.hxx>
#include <xsd/cxx/xml/dom/serialization-source.hxx>

namespace prj
{
  namespace srl
  {
    void
    operator<< (::xercesc::DOMElement& e, const FeatureRevolve& i)
    {
      e << static_cast< const ::xml_schema::Type& > (i);

      // featureBase
      //
      {
        ::xercesc::DOMElement& s (
          ::xsd::cxx::xml::dom::create_element (
            "featureBase",
            e));

        s << i.featureBase ();
      }

      // picks
      //
      {
        ::xercesc::DOMElement& s (
          ::xsd::cxx::xml::dom::create_element (
            "picks",
            e));

        s << i.picks ();
      }

      // axisPicks
      //
      {
        ::xercesc::DOMElement& s (
          ::xsd::cxx::xml::dom::create_element (
            "axisPicks",
            e));

        s << i.axisPicks ();
      }

      // axisOrigin
      //
      {
        ::xercesc::DOMElement& s (
          ::xsd::cxx::xml::dom::create_element (
            "axisOrigin",
            e));

        s << i.axisOrigin ();
      }

      // axisOriginLabel
      //
      {
        ::xercesc::DOMElement& s (
          ::xsd::cxx::xml::dom::create_element (
            "axisOriginLabel",
            e));

        s << i.axisOriginLabel ();
      }

      // axisDirection
      //
      {
        ::xercesc::DOMElement& s (
          ::xsd::cxx::xml::dom::create_element (
            "axisDirection",
            e));

        s << i.axisDirection ();
      }

      // axisDirectionLabel
      //
      {
        ::xercesc::DOMElement& s (
          ::xsd::cxx::xml::dom::create_element (
            "axisDirectionLabel",
            e));

        s << i.axisDirectionLabel ();
      }

      // angle
      //
      {
        ::xercesc::DOMElement& s (
          ::xsd::cxx::xml::dom::create_element (
            "angle",
            e));

        s << i.angle ();
      }

      // angleLabel
      //
      {
        ::xercesc::DOMElement& s (
          ::xsd::cxx::xml::dom::create_element (
            "angleLabel",
            e));

        s << i.angleLabel ();
      }

      // axisType
      //
      {
        ::xercesc::DOMElement& s (
          ::xsd::cxx::xml::dom::create_element (
            "axisType",
            e));

        s << i.axisType ();
      }

      // generatedMap
      //
      {
        ::xercesc::DOMElement& s (
          ::xsd::cxx::xml::dom::create_element (
            "generatedMap",
            e));

        s << i.generatedMap ();
      }

      // lastMap
      //
      {
        ::xercesc::DOMElement& s (
          ::xsd::cxx::xml::dom::create_element (
            "lastMap",
            e));

        s << i.lastMap ();
      }

      // oWireMap
      //
      {
        ::xercesc::DOMElement& s (
          ::xsd::cxx::xml::dom::create_element (
            "oWireMap",
            e));

        s << i.oWireMap ();
      }
    }

    void
    revolve (::std::ostream& o,
             const ::prj::srl::FeatureRevolve& s,
             const ::xml_schema::NamespaceInfomap& m,
             const ::std::string& e,
             ::xml_schema::Flags f)
    {
      ::xsd::cxx::xml::auto_initializer i (
        (f & ::xml_schema::Flags::dont_initialize) == 0);

      ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
        ::prj::srl::revolve (s, m, f));

      ::xsd::cxx::tree::error_handler< char > h;

      ::xsd::cxx::xml::dom::ostream_format_target t (o);
      if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
      {
        h.throw_if_failed< ::xsd::cxx::tree::serialization< char > > ();
      }
    }

    void
    revolve (::std::ostream& o,
             const ::prj::srl::FeatureRevolve& s,
             ::xml_schema::ErrorHandler& h,
             const ::xml_schema::NamespaceInfomap& m,
             const ::std::string& e,
             ::xml_schema::Flags f)
    {
      ::xsd::cxx::xml::auto_initializer i (
        (f & ::xml_schema::Flags::dont_initialize) == 0);

      ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
        ::prj::srl::revolve (s, m, f));
      ::xsd::cxx::xml::dom::ostream_format_target t (o);
      if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
      {
        throw ::xsd::cxx::tree::serialization< char > ();
      }
    }

    void
    revolve (::std::ostream& o,
             const ::prj::srl::FeatureRevolve& s,
             ::xercesc::DOMErrorHandler& h,
             const ::xml_schema::NamespaceInfomap& m,
             const ::std::string& e,
             ::xml_schema::Flags f)
    {
      ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
        ::prj::srl::revolve (s, m, f));
      ::xsd::cxx::xml::dom::ostream_format_target t (o);
      if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
      {
        throw ::xsd::cxx::tree::serialization< char > ();
      }
    }

    void
    revolve (::xercesc::XMLFormatTarget& t,
             const ::prj::srl::FeatureRevolve& s,
             const ::xml_schema::NamespaceInfomap& m,
             const ::std::string& e,
             ::xml_schema::Flags f)
    {
      ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
        ::prj::srl::revolve (s, m, f));

      ::xsd::cxx::tree::error_handler< char > h;

      if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
      {
        h.throw_if_failed< ::xsd::cxx::tree::serialization< char > > ();
      }
    }

    void
    revolve (::xercesc::XMLFormatTarget& t,
             const ::prj::srl::FeatureRevolve& s,
             ::xml_schema::ErrorHandler& h,
             const ::xml_schema::NamespaceInfomap& m,
             const ::std::string& e,
             ::xml_schema::Flags f)
    {
      ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
        ::prj::srl::revolve (s, m, f));
      if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
      {
        throw ::xsd::cxx::tree::serialization< char > ();
      }
    }

    void
    revolve (::xercesc::XMLFormatTarget& t,
             const ::prj::srl::FeatureRevolve& s,
             ::xercesc::DOMErrorHandler& h,
             const ::xml_schema::NamespaceInfomap& m,
             const ::std::string& e,
             ::xml_schema::Flags f)
    {
      ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
        ::prj::srl::revolve (s, m, f));
      if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
      {
        throw ::xsd::cxx::tree::serialization< char > ();
      }
    }

    void
    revolve (::xercesc::DOMDocument& d,
             const ::prj::srl::FeatureRevolve& s,
             ::xml_schema::Flags)
    {
      ::xercesc::DOMElement& e (*d.getDocumentElement ());
      const ::xsd::cxx::xml::qualified_name< char > n (
        ::xsd::cxx::xml::dom::name< char > (e));

      if (n.name () == "revolve" &&
          n.namespace_ () == "http://www.cadseer.com/prj/srl")
      {
        e << s;
      }
      else
      {
        throw ::xsd::cxx::tree::unexpected_element < char > (
          n.name (),
          n.namespace_ (),
          "revolve",
          "http://www.cadseer.com/prj/srl");
      }
    }

    ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument >
    revolve (const ::prj::srl::FeatureRevolve& s,
             const ::xml_schema::NamespaceInfomap& m,
             ::xml_schema::Flags f)
    {
      ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
        ::xsd::cxx::xml::dom::serialize< char > (
          "revolve",
          "http://www.cadseer.com/prj/srl",
          m, f));

      ::prj::srl::revolve (*d, s, f);
      return d;
    }
  }
}

#include <xsd/cxx/post.hxx>

// Begin epilogue.
//
//
// End epilogue.

